---
abstract: 'Manipulate CPU affinities on FreeBSD'
author:
  - 'Sergey Aleynikov <sergey.aleynikov@gmail.com>'
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BSD-Process-Affinity
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0
  Bit::Vector: 7.0
  Exporter: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0301
